services:
  racket-stringing:
    container_name: racket-stringing
    build:
      context: https://github.com/MS-Setjun/Racket-Stringer.git
      dockerfile: Dockerfile
    image: racket-stringing-app:latest
    restart: unless-stopped
    volumes:
      - /mnt/swimming/racket-stringing:/app/data
    environment:
      - APP_DATA_DIR=/app/data
    ports:
      - 8501:8501